executor: cluster-generic
cluster-generic-submit-cmd: 
  export OMP_NUM_THREADS=1 &&
  export TMPDIR=/work &&
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.ntasks}
    --nodes={resources.nodes}
    --mem={resources.mem_mb}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{wildcards}-%j.out
    --time={resources.time}
    --gpus-per-task={resources.gpus}
default-resources:
  - partition=genoaxq,milanq,fpgaq,defq
  - mem_mb=0
  - time="30:00"
  - ntasks=1
  - nodes=1
  - gpus=0
  - hint=nomultithread
restart-times: 0
max-jobs-per-second: 20
max-status-checks-per-second: 1
local-cores: 20
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
rerun-triggers: mtime